### ISSUE TITLE
Install separate from pown, no response.

### ISSUE THREAD

**Issue by Metroxe** [pownjs/whoarethey#2]
I installed as the README instructured

When I run `./node_modules/.bin/pown-cli whoarethey`

I get no response, no errors or crashing

![image](https://user-images.githubusercontent.com/19210023/54646049-22553680-4a5b-11e9-9016-96bc318dd709.png)

**Comment by pdparchitect** [comment]
I will update the documentation. You will need to specify where the root of pown is.

```POWN_ROOT=. ./node_modules/.bin/pown-cli whoarethey```

**Comment by infernuxmonster** [comment]
I have the same issue, specifiying root like this doesn't solve it for me.

**Comment by Metroxe** [comment]
this did not solve the issue. I tried to install globally as shown here. Still cannot get a response

![image](https://user-images.githubusercontent.com/19210023/54854018-c7b41880-4cae-11e9-8c32-6ff8e5132fa4.png)

Is it possibly my node version?

**Comment by felipe19930** [comment]
I used `yarn` to install globally and got the same behavior, but I finally got it to work.

First make sure you have the output of `yarn global bin` in your `PATH` variable, e.g.:

```bash
$ export PATH="$(yarn global bin):$PATH"
```

Then install `pown`, globally:

```
$ yarn global add pown
```

Now to actually run `pown`:

```bash
$ POWN_ROOT="$(yarn global dir)/node_modules/@pown/whoarethey" pown whoarethey 1password
```

And of course you add that big-ass command as an alias in your `~/.bashrc` / `~/.zshrc`, etc.:

```bash
alias pown="POWN_ROOT=$(yarn global dir)/node_modules/@pown/whoarethey pown"
```

Not sure if there's an easier way to do this (I'm not familiar with NodeJS), but hey, works for me™

**Comment by pdparchitect** [comment]
Perhaps it is not clear from the documentation but pown is made from several discrete parts. It is not really a framework like Metasploit. One part is the CLI. Another is the module system. We have some modules like this one as well. This allow for modules to be small and lean and reused as libraries without indirectly including the rest.

This makes it difficult to install commands like this one globally. You can install it locally or install pown globally or install it via pown globally. If you want to create a standalone version of this common you will need the CLI at the very least and do what you did above.

Alternatively you can make your own distributions. You can take any number of pown commonds and assamble them into a module like pown. Only the commands you depend on will be included. Imagine you want to build a pown distributed for web security, osint, etc.

**Comment by Metroxe** [comment]
I did fix my problem for the global and local installation. I was using node `v8.11.4`, when I switched to `v10.15.3`, everything worked via the instructions on the README

**Comment by pdparchitect** [comment]
I would recommend 11 for full compatability with all modules but this one should work in 10.
